### ISSUE TITLE
TurnstileObject.ready should take a callback

### ISSUE THREAD

**Issue by mithodin** [Le0Developer/turnstile-types#1]
See https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#explicitly-render-the-turnstile-widget
turnstile.ready() needs to be called with a callback, which is called once turnstile is ready.

**Comment by Le0Developer** [comment]
Oops, thanks.
Fyi, `turnstile.ready()` calls the callback when the DOM is ready (because turnstile is already ready at the point the API is available), it exists purely for reCaptcha compatibility, so imo you shouldn't use it (especially because you should be embedding the turnstile script with `defer`, so Turnstile can't be ready before the DOM is).

**Comment by Le0Developer** [comment]
Fixed in v1.2.0 released a few minutes ago.
